### ISSUE TITLE
Use Travis CI to test on OS-X and Linux

### ISSUE THREAD

**Issue by rweigel** [hapi-server/client-python#13]
At present, there are tests for Python 2.7, 3.5-3.8, and these tests are run on virtual machines. These tests need to be run automatically using Travis CI.

The plotting tests need to be split into tests that produce images and are compared to reference images. The GUI tests will still need to be ad-hoc.

**Comment by hbatta** [comment]
Raised a pull request can you review it and let me know.

**Comment by rweigel** [comment]
This page https://github.com/hapi-server/client-python/pull/20 says the builds are failing. I'd prefer to do a pull request that leads to the tests passing.

**Comment by hbatta** [comment]
Yes, they are failing but that is not due to the travis setup. Its due to the code written which is not working in windows env. 10/11 test cases are passing. There is an issue with one particular test case.

**Comment by rweigel** [comment]
I think that we should wait until we get all tests passing. I think it is
better to commit a working Travis for OS-X and Linux first and then do a
different pull request when Windows is working. This way when we do commits
to the repository, we don't always get a failure independent of whether our
commit actually broke something.

**Comment by hbatta** [comment]
Okay, I'll raise a pull request for OSX and linux builds.
