### ISSUE TITLE
Inconsistencies with first data point retrieval. 

### ISSUE THREAD

**Issue by angelgutarra** [hapi-server/client-python#23]
If the satellite has one minute intervals then it does not include the first data point such as with cluster1. 

```python
from hapiclient import hapi
server     = 'http://hapi-server.org/servers-dev/SSCWeb/hapi';
dataset    = 'cluster1';
parameters = 'X_GSE'
start      = '2002-01-02T10:00:00.000Z';
stop       = '2002-01-02T10:03:00.000Z';
data, meta = hapi(server, dataset, parameters, start, stop)
print(data)
```

```bash
[('2002-002T10:01Z', 8.83637772) ('2002-002T10:02Z', 8.84128551)]
```

If the satellite has 12 minute intervals then it does include the first data point such as with ace. 

```python
server     = 'http://hapi-server.org/servers-dev/SSCWeb/hapi';
dataset    = 'ace';
parameters = 'X_GSE'
start      = '2002-01-02T10:00:00.000Z';
stop       = '2002-01-02T10:24:00.000Z';
data, meta = hapi(server, dataset, parameters, start, stop)
print(data)
```

```bash
[('2002-002T10:00Z', 241.19067616) ('2002-002T10:12Z', 241.19213305)]
```

This might be an issue with SSCWEB because they also have the same pattern as you can see from the Ace and Cluster1 output txt files. 

[cluster1_output.txt](https://github.com/hapi-server/client-python/files/5256948/cluster1_output.txt)

[ace_output.txt](https://github.com/hapi-server/client-python/files/5256970/ace_output.txt)

**Comment by angelgutarra** [comment]
**update**: The reason that SSCWEB did not include the first point in Cluster1 was because I did not put in the proper time format. Cluster1 recorded its data not at the minute mark but at 30 second mark. In order to capture this I needed to input the time format like this **HH:MM:SS** instead of **HH:MM**, doing this gave the correct results of inclusive values for start and ending points. (see cluster1_output_correct.txt below) 

Looking at the time given by Hapi it does not provide any seconds category. Perhaps the error stems from Hapi requesting time in the format HH:MM. Solving the inclusivity issue might just have to be changing the time format to HH:MM:SS.

**Comment by rweigel** [comment]
There are several issues here that we can discuss in detail when we meet next. I had written a long post here but never submitted it. A few quick points:

Try the latest version of the Python HAPI client:

```
pip install 'git+https://github.com/hapi-server/client-python' --upgrade
```

Also, don't use `servers-dev` unless it has something that is not available from `servers`.

Make sure that you are not using cached data - an earlier version of the SSCWeb HAPI server was not requesting data from SSCWeb at its highest time resolution. I don't think the issue has ever been with the HAPI Python client. The issue of the server was not requesting the highest time resolution from SSCWeb was fixed about a month ago. The remaining issue is that the server was not removing the last time value. SSCWeb uses inclusive times for start/stop and HAPI is inclusive/exclusive.

Hapi should be HAPI and SSCWEB is SSCWeb.

**Comment by angelgutarra** [comment]
The upgrade command resolved the issue. Thank you.

**Comment by rweigel** [comment]
This is unexpected. We'll need to make sure we understand why this worked. From what I recall, there was not a change in the Python client that should have changed things.
