### ISSUE TITLE
Error in Windows when pythonshell() is called

### ISSUE THREAD

**Issue by AyrisA** [hapi-server/client-python#25]
`pythonshell()` fails on a missing key when running the client on a Windows10 installation of python.  

It is trying to use the os.environ key `'_'` which doesn't exist.

I can avoid the problem by turning setting the logging option to `False`, but I'd really like to have logging on.
My local workaround is to modify `pythonshell` in `util.py` as follows:

```
def pythonshell():
    """Determine python shell

    pythonshell() returns

    'shell' (started python on command line using "python")
    'ipython' (started ipython on command line using "ipython")
    'ipython-notebook' (running in Spyder or started with "ipython qtconsole")
    'jupyter-notebook' (running in a Jupyter notebook)

    See also https://stackoverflow.com/a/37661854
    """

    from os import environ, path
    env = environ
    shell = 'shell'

    if '_' in env.keys():
      program = path.basename(env['_'])

      if 'jupyter-notebook' in program:
          shell = 'jupyter-notebook'
      elif 'JPY_PARENT_PID' in env or 'ipython' in program:
          shell = 'ipython'
          if 'JPY_PARENT_PID' in env:
              shell = 'ipython-notebook'

    return shell
```

**Comment by rweigel** [comment]
from os import environ, path
    env = environ
    shell = 'shell'
    program = path.basename(env['_'])

    if 'jupyter-notebook' in program:
        shell = 'jupyter-notebook'
    elif 'JPY_PARENT_PID' in env or 'ipython' in program:
        shell = 'ipython'
        if 'JPY_PARENT_PID' in env:
            shell = 'ipython-notebook'

    return shell

**Comment by rweigel** [comment]
Thanks for your note. I hit the wrong button after copying the existing code in a comment above.

We'll look into this some more and post and update here.

**Comment by rweigel** [comment]
@hbatta and @KSR4599 if you have access to a Windows 10 machine, would you look into this?

**Comment by AyrisA** [comment]
> Thanks for your note. I hit the wrong button after copying the existing code in a comment above.
> 
> We'll look into this some more and post and update here.

Great! I very much like having this client in my toolkit.  Thanks for developing.
-Ayris

**Comment by hbatta** [comment]
Will look into it professor.

**Comment by KSR4599** [comment]
Inorder to make it work for windows,  `get_ipython().__class__.__name__`  seems like a better option.
```
def pythonshell():
    try:
        shell = get_ipython().__class__.__name__
        if shell == 'ZMQInteractiveShell':
            shell='jupyter-notebook' 
        elif shell == 'TerminalInteractiveShell':
            shell='ipython' 
    except NameError:
        shell = 'shell'
    return shell
```
