### ISSUE TITLE
Feature request: datetime2hapitime 

### ISSUE THREAD

**Issue by kurtsansom** [hapi-server/client-python#46]
`hapitime2datetime` exists but it doesn't appear to have the inverse.

e.g. something like
```
def datetime2hapitime_str(time):
  return time.isoformat()[0:19] + **"Z"**
```

or
```
class hapitime(datetime.datetime):
  def hapiformat(self, sep='T', timespec='auto'):
      """Return the time formatted according to hapi data specification.

      Basically just adds a z on the end.
      but maybe it's more complicated than that.
      """

      return self.isoformat()[0:19] + "Z"
```

  `hapitime2datetime` can ingest a string, but it's common to toggle back and forth, i.e. its easier to compare times when they are datetime objects . 
   it may be more complicated to subclass `datetime` and add a `hapiformat` method that seems like another option.

**Comment by rweigel** [comment]
Code has been added.
