### ISSUE TITLE
Handling non-Z times from earlier servers (e.g. SSCWeb)

### ISSUE THREAD

**Issue by sandyfreelance** [hapi-server/client-python#48]
SSCWeb can fetch and plot specific items, but while it fetches it cannot plot 'all data' because calls with parameters='' lack the trailing 'Z' on Time, while calls that specify a parameter (e.g. parameters='X_GSE') do include the trailing 'Z' on Time.

Historically Jeremy notes earlier HAPI servers may not have enforced Z-ness. Thus fixing this by allowing 'hapiclient' to add a 'Z' if missing, and/or 'hapiplot' to accept Z-less Times is recommended.

Example) Fetching data from SSCWeb likewise:

  **parameters=''X_GSE,Y_GSE,Z_GSE'** --> WORKS
  **hapiplot(data,meta)** WORKS

BUT

  **parameters=''** --> returns all data properly
  **hapiplot(data,meta)** FAILS with "HAPI Times must have trailing Z'

(happens regardless of whether a trailing 'Z' is on the start/stop values, i.e. adding 'Z' does not change the fetch).

With SSCWeb, fetching specific data items returns 'Time' in proper format with the trailing 'Z' plus the data items:

`>>> print(data)`

```
[(b'2001-001T05:00:00Z', 238.69484332, 26.03684468, 10.72117284)
 (b'2001-001T05:12:00Z', 238.69630999, 26.02820798, 10.72732475)
 (b'2001-001T05:24:00Z', 238.69779744, 26.01956185, 10.73349166)
 (b'2001-001T05:36:00Z', 238.69929104, 26.01092127, 10.73965309)
 (b'2001-001T05:48:00Z', 238.70078845, 26.00228668, 10.74581451)]

```
 

But just passing parameters='' returns Time with no 'Z':

`[(b'2001-001T05:00:00', 70.50316721, -214.85135097, -81.46342422, -19.8121, 288.1672, 70.44705783, -214.86715178, -81.47029038, -19.8138, 288.1524, -85.61335215, 209.2896403 , -81.46342422, -19.8121, 112.2478, '12:29:00', -207.16328781, -15.24132501, -120.90973197, -30.2025, 184.2078, '12:27:52', 238.69484332, 26.03684468, 10.72117284, 2.5566, 6.2252, '12:24:54', 238.69484332, 25.19845512, 12.56577577, 2.9969, 6.0263, 206.18914536, 25.19845512, -120.90973197, -30.2025, 6.9676, '12:27:52', 1.e+31, 1.e+31, 1.e+31, 1.e+31, 1.e+31, 1.e+31, 1.e+31, 1.e+31, 1.e+31, 1.e+31, 1.e+31, 1.e+31, 240.34993049, 1.e+31, 1.e+31, 225.91582426, 229.41263207, 321.8, 86.8, 'Intpl_Med', 'S_Mid-Lat', 'None', 'None', 1.e+31, 1.e+31, 1.e+31)`

[etc]

Example code:
```
# SSCWeb example
from hapiclient import hapi
from hapiplot import hapiplot

server     = 'http://hapi-server.org/servers/SSCWeb/hapi'
dataset    = 'ace'
start      = '2001-01-01T05:00:00Z'
stop       = '2001-01-01T06:00:00Z'
parameters = 'X_GSE,Y_GSE,Z_GSE'
opts       = {'logging': True, 'usecache': False}
 
# Get parameter data. See section 5 for for information on getting available datasets and parameters
data, meta = hapi(server, dataset, parameters, start, stop, **opts)
print(data)
hapiplot(data,meta)
```

**Comment by rweigel** [comment]
Closed by https://github.com/hapi-server/server-nodejs/commit/58849f4e7d8b54ecc7bf7126b2e4325a6c138a06
