### ISSUE TITLE
typo in PyPi link to demo script

### ISSUE THREAD

**Issue by sandyfreelance** [hapi-server/client-python#50]
In https://pypi.org/project/hapiclient/ 
`"Basic usage examples for various HAPI servers are given in [hapi_demo.py](https://github.com/hapi-server/client-python/blob/master/hapi_demo.py%3E)"`

... there's an erroneous extra ">" aka %3E in the URL, that means it's a bad link.  Easy edit to fix for someone with permissions.

**Comment by rweigel** [comment]
Closed by 3fa9c8287e8c7e9c579047828ddbaf65adc215da
