### ISSUE TITLE
Client assumes CSV columns are in same order as parameters in info JSON file

### ISSUE THREAD

**Issue by lkilcommons** [hapi-server/client-python#6]
I'm pretty sure this isn't really a bug in the client, but I'm going to raise this issue here and we can move discussion elsewhere if needed, since I encountered the problem while trying to use the Python client.

I was trying to download some data from NASA CDAWeb, like so:

```{python}
import numpy as np
import os,glob,tempfile,datetime
from hapiclient import hapi

if __name__ == '__main__':

    startdt = datetime.datetime(2010,1,15,0,43,27)
    enddt = datetime.datetime(2010,1,15,1,12,14)
    satnum = 16
    cdfvars = ['ELE_DIFF_ENERGY_FLUX',
                'SC_GEOCENTRIC_LAT',
                'SC_GEOCENTRIC_LON',
                'SC_AACGM_LAT',
                'SC_AACGM_LTIME',
                'ELE_TOTAL_ENERGY_FLUX',
                'ELE_AVG_ENERGY']

    server     = 'https://cdaweb.gsfc.nasa.gov/hapi'
    dataset    = 'DMSP-F{:02d}_SSJ_PRECIPITATING-ELECTRONS-IONS'.format(satnum)
    start      = startdt.isoformat()
    stop       = enddt.isoformat()
    parameters = (',').join(cdfvars) # Expects a comma seperated string
    opts       = {'logging': True,'format':'csv'}

    info = hapi(server,dataset)

    # Get data
    data, meta = hapi(server, dataset, parameters, start, stop, **opts)

    print('Geocentric Latitude (min,median,max)')
    print(np.nanmin(data['SC_GEOCENTRIC_LAT']))
    print(np.nanmedian(data['SC_GEOCENTRIC_LAT']))
    print(np.nanmax(data['SC_GEOCENTRIC_LAT']))

    print('Geomagnetic Latitude (min,median,max)')
    print(np.nanmin(data['SC_AACGM_LAT']))
    print(np.nanmedian(data['SC_AACGM_LAT']))
    print(np.nanmax(data['SC_AACGM_LAT']))
```
But I got very unexpected results:

```
Geocentric Latitude (min,median,max)
45.0
66.6
80.8
Geomagnetic Latitude (min,median,max)
0.0
33800000.0
815000000000.0
```
So some of the variables produced sensible data, and some don't. Strange.

After a couple days of checking, I've found what was going wrong: if you request multiple variables (parameters), the client assumes that a server will write data to the binary file or columns to the CSV in the same order as they appear in the JSON file from the info endpoint. Naively, I had expected that the columns of the CSV would write out in the order of the parameter list, and it turns out this is exactly what the CDAWeb server does, but it not what the HAPI client expects. I also tried playing around with the pytest tests and tried to write a test to demonstrate this problem using the HAPI test server, but the test server *does* write the CSV columns in the order the client expects.

So, is this a misconfiguration with the NASA CDAWeb server (in which case I should probably talk to Bobby Candey)? But is this an overlooked aspect in the HAPI specifications? I did a quick read-though and didn't find mention about how parameters should be ordered in the data stream, but it's possible I overlooked it.

**Comment by lkilcommons** [comment]
Update: I've been corresponding with Bobby Candey, and he's set me straight on the HAPI spec, in that it calls only for parameter arguments in the order they are listed in the JSON output from the info endpoint.
So part of the problem is my putting the parameters in the wrong order.

**Comment by rweigel** [comment]
Thanks for the detailed report. This is a bug in the client:

```
 print(np.nanmax(data['SC_AACGM_LAT'])) # Wrong data
```

The fix will be to re-order parameter list in request URL https://github.com/hapi-server/client-python/blob/master/hapiclient/hapi.py#L263

Client should also re-order data ndarray so that output of, e.g., `data[0]`, is consistent with order user requested.

**Comment by rweigel** [comment]
Decided to throw error if requested parameters are not in same order as that in info response. Error message indicated desired order.

In HAPI 2.0, there is an ambiguity in how this is handled by the server. In HAPI 2.1, a request with parameters out-of-order is a 1411 error. Allowing users to specify parameters out-of-order in client creates complications with caching and would require significant modification of existing code.
