### ISSUE TITLE
Fails to Download All of the Request

### ISSUE THREAD

**Issue by Tiger767** [hapi-server/client-python#60]
Requesting 2018/09/01 to 2018/10/01 results in data only to 2018/09/23 with no apparent reason.

```Python

from hapiclient import hapi
from hapiclient import hapitime2datetime

server = 'https://cdaweb.gsfc.nasa.gov/hapi'
options = {'logging': True, 'usecache': True, 'cachedir': './hapicache'}

start = '2018-09-01T10:00:00Z'
stop = '2018-10-01T00:00:00Z'
fpi_dis_data, meta = hapi(server, 'MMS1_FPI_FAST_L2_DIS-MOMS', 'mms1_dis_numberdensity_fast,mms1_dis_bulkv_gse_fast', start, stop, **options)

# Note how the time stops at 9-23
print(fpi_dis_data)

# change start time to be pass 23rd
start = '2018-09-24T10:00:00Z'
stop = '2018-10-01T00:00:00Z'
fpi_dis_data, meta = hapi(server, 'MMS1_FPI_FAST_L2_DIS-MOMS', 'mms1_dis_numberdensity_fast,mms1_dis_bulkv_gse_fast', start, stop, **options)

```

As seen with the code above, the first request fails to grab all the data.

Using another source for the data (Pyspedas), I was able to find that there are gaps at these times: 
 (Actual Time, Length of Gap)
[(Timestamp('2018-09-06 18:01:54.331409920'),
  Timedelta('0 days 04:29:55.650216192')),

 (Timestamp('2018-09-07 23:59:53.636424960'),
  Timedelta('0 days 02:01:56.737405952')),

 (Timestamp('2018-09-08 20:14:22.353390848'),
  Timedelta('0 days 19:31:25.342690048')),

 (Timestamp('2018-09-11 09:19:56.269243904'),
  Timedelta('0 days 18:33:39.710816256')),

 (Timestamp('2018-09-12 05:51:57.021147136'),
  Timedelta('0 days 05:30:39.487346688')),

 (Timestamp('2018-09-14 04:50:58.596395008'),
  Timedelta('0 days 22:07:37.471473920')),

 (Timestamp('2018-09-15 04:56:57.111435008'),
  Timedelta('0 days 02:05:52.509689088')),

 (Timestamp('2018-09-17 00:24:58.227958016'),
  Timedelta('1 days 02:24:45.825616128')),

 (Timestamp('2018-09-19 14:07:58.500301056'),
  Timedelta('0 days 01:59:33.095218944')),

 (Timestamp('2018-09-19 19:54:55.697478144'),
  Timedelta('0 days 02:20:49.267862016')),

 (Timestamp('2018-09-20 00:05:28.513041920'),
  Timedelta('0 days 16:45:16.607410944')),

 (Timestamp('2018-09-20 18:48:57.157449984'),
  Timedelta('0 days 03:46:39.534276864')),

 (Timestamp('2018-09-21 00:04:51.721601024'),
  Timedelta('0 days 02:15:58.465722112')),

 (Timestamp('2018-09-22 15:45:00.044934912'),
  Timedelta('0 days 22:26:47.481163008')),

 (Timestamp('2018-09-23 18:09:59.603328'),
  Timedelta('0 days 03:51:39.499502848')),

 (Timestamp('2018-09-24 04:04:57.234031872'),
  Timedelta('0 days 03:16:44.251121152')),

 (Timestamp('2018-09-25 18:19:27.313796096'),
  Timedelta('0 days 11:40:06.365180928')),

 (Timestamp('2018-09-26 08:14:56.221938176'),
  Timedelta('0 days 07:06:40.803796992')),

 (Timestamp('2018-09-26 23:47:56.712483840'),
  Timedelta('2 days 03:18:15.013784320')),

 (Timestamp('2018-09-29 12:14:22.431373824'),
  Timedelta('0 days 08:11:47.656691200')),

 (Timestamp('2018-09-30 05:24:22.303053824'),
  Timedelta('0 days 02:11:50.825856256')),

 (Timestamp('2018-10-01 09:18:49.784121088'),
  Timedelta('0 days 11:22:38.024400896'))]

Note 27th and 28th are missing, but that does not explain what is happening.

**Comment by rweigel** [comment]
I've confirmed that this is not due to the python client and submitted a report to https://github.com/hapi-server/server-issues/issues/6.
