### ISSUE TITLE
confusing message from plotting client

### ISSUE THREAD

**Issue by jbfaden** [hapi-server/client-python#8]
I see an issue with the plotting client, where I get a red error screen with "hapiclient version 0.1.3b\nCould not parse time value 20256Z" :

http://hapi-server.org/plot?usecache=false&usedatacache=false&server=http://jfaden.net/HapiServerDemo/hapi&id=WFR_E_B&parameters=Time&time.min=2017-02-09T00:00:02.478Z&time.max=2017-02-09T23:59:56.968Z

I found that the error message is confusing because I didn't realize that the issue was with the length of the string. (My info reports that the times will be 24 characters, while I was returning 30 characters.)  In fact, I thought there was an issue with the plotter at first, before I finally realized this was an error on my end.

**Comment by rweigel** [comment]
Seems like the error message should have included the format string that it was attempting to use:

https://github.com/hapi-server/client-python/blob/master/hapiclient/hapi.py#L856

I should probably add a suggestion of running the metadata through the validator when errors like this occur as I don't want to be adding too much metadata validation. Then again, if there are a few common errors, probably they should be included in the client.

**Comment by jbfaden** [comment]
That would work.  Just something to get the developer to think about the length as well as the content.

**Comment by rweigel** [comment]
Closed due to #31. Will pick up there.
